### ISSUE TITLE
Uncaught Exceptions are logged at 'info' level, not 'error'

### ISSUE THREAD

**Issue by huhtari** [adrianhall/winston-splunk-httplogger#1]
This seems to happen because `exceptionsLevel` is not set in `SplunkStreamEvent` construction. 

Just calling `winston.Transport.call()` (from which `SplunkStreamEvent` is inherited) constructor function fixes this.

Or is there a reason not to call the constructor? For example `Console` and `DailyRotateFile` transports do it.

**Comment by adrianhall** [comment]
I suspect the Splunk SDK has updated since I wrote this and I no longer have a configuration set up (it's been over a year).  Happy to take a pull request for an update.

**Comment by adrianhall** [comment]
Fixed in 67b651c

**Comment by adrianhall** [comment]
Fixed in v1.2.2 - sorry for the delay.
