### ISSUE TITLE
Getting Error While logging

### ISSUE THREAD

**Issue by GeekRishabh** [adrianhall/winston-splunk-httplogger#14]
Error: Incorrect index

{"message":{"msg":"Queue :: #45 Removed Processed Job","functionName":"removeProcessedJob"},"level":"info"}
ERROR: Error: Incorrect index

`CONTEXT {
  message: '{"source":"winston","sourcetype":"winston-splunk-logger","index":"winston-index","time":"1578488973.582","event":{"message":{"msg":{"msg":"Queue ' +
    ':: #45 Removed Processed ' +
    'Job","functionName":"removeProcessedJob"},"meta":{"message":{"msg":"Queue ' +
    ':: #45 Removed Processed ' +
    'Job","functionName":"removeProcessedJob"},"level":"info"}},"severity":"info"}}',
  severity: 'info',
  metadata: {}
}`

**Comment by adrianhall** [comment]
The error is from the remote end, so it is likely you don't have winston-index set up on the server.
