### ISSUE TITLE
using splunk w/o port number on url

### ISSUE THREAD

**Issue by VahidMhrb** [adrianhall/winston-splunk-httplogger#18]
hi, I am using this module to log data into splunk. For some reason i have a proxy server to transfer trafic to splunk event collector, my proxy have no port number on url, but it will be added on run time. Am I doing something wrong?

`var splunkSettings = {
    token: 'mySplunkToken',
    url : "https://somedomainwithoutportnumber.com/services/collector"
};
`
but at run time i see winston try to contract with https://somedomainwithoutportnumber.com:8088/services/collector

**Comment by adrianhall** [comment]
Default https port is 443.  When the port is not specified, it is set to the default port for splunk.  If you need to alter that, you will want to specify 443.
