### ISSUE TITLE
Default index overrides token settings on Splunk server

### ISSUE THREAD

**Issue by robpc** [adrianhall/winston-splunk-httplogger#22]
I noticed an issue when updating from `2.0.0` to `2.3.3`. The newer version sets a default index to `winston-index`. That is a breaking change for anyone whose index is not `winston-index` (almost all projects I assume). It looks like setting a default index was added in #10, though not the explicit goal of that change.

In our setup almost all our tokens have indexes automatically applied and access is limited to those indexes. Most of our code therefore does not set the index since creation and management of the tokens is not under our control. Unlike other splunk metadata if there is no index called `winston-index` or the token doesn't have access to that index then the logs are "lost" as only an admin will be able to see the ingestion errors. 

Obviously, setting the index manually is a workaround, but because it will most likely to not work out of the box, I think that makes it an "unreasonable default" so to speak and would prefer index not to be set unless set by the user.

**Comment by adrianhall** [comment]
This is no longer under active development.  I'll happily accept a PR, but I don't have a Splunk instance to test against any more.

**Comment by adrianhall** [comment]
Cleaning up
