### ISSUE TITLE
Winston 3.x.x Support

### ISSUE THREAD

**Issue by e2he** [adrianhall/winston-splunk-httplogger#6]
Howdy! Thanks for maintaining this package.

I am starting to use this package on a Winston 3.x.x project, and I get a lot of legacy API warnings due to the transport class not being updated with 3.x.x support. I am happy to submit a PR that provides that support.

I was wondering what the appetite is for continuing support for Winston 2.x.x? Would it be okay to abandon 2.x.x? Users could pin their `winston-splunk-httplogger` if they were unable to move to Winston 3.x.x (which was released over 6 months ago).

**Comment by adrianhall** [comment]
We can do a release that ups the major version and drops support for Winston 2.x.x.  I'd like to include an error message that is clearly displayed if used with Winston 2.x.x if possible.

I am no longer actively maintaining this package as I do not have the Splunk instance running any more to test it before release.  If you would like to take it over, I'll happily transfer it to you.

If not, I will accept the PR and release as a new major version.  Please ensure that you update the README to indicate the Winston 3.x.x and that it is tested appropriately (and include any tests you did against what versions of Splunk)

Thanks!.

**Comment by e2he** [comment]
Thanks for the quick response! I'm not sure if my organization is willing to take over maintenance of the package, while I sort that out I submitted #7 with support for Winston 3.

**Comment by adrianhall** [comment]
Released v2.0.0 - thank you for the contribution.
