### ISSUE TITLE
Batching with winston-splunk-httplogger don’t seem to be implemented or documented right

### ISSUE THREAD

**Issue by NitzanZ25** [adrianhall/winston-splunk-httplogger#78]
Hi, thanks for maintaining this package :)

I’m trying to batch my logging requests, 
I’ve debugged Winston and this package and I’ve tried few things, I understood that putting the 
`batchInterval, maxBatchCount` Inside splunk object works (your documentation says different), maxBatchCount is not implemented (also after putting value in to it it’s still setting to default - 0)
So I put it artificially with `server.config.maxBatchCount = value`

Ended up with no logging at all 
I would like to see an example of use of batching or a solution to my problem please :)

I’m using Winston 3.3.3, winston-splunk-httplogger 2.3.3

**Comment by adrianhall** [comment]
Hi @NitzanZ25 - unfortunately, this package is NOT maintained any more (beyond doing the regular security updates).  I don't have an environment nor any time to maintain it.  However, no-one else has stepped forward to take it over either.

Sorry I can't help!
