### ISSUE TITLE
Not able to change index in metadata for splunk

### ISSUE THREAD

**Issue by razzdrawon** [adrianhall/winston-splunk-httplogger#9]
Im trying to configure a different source, sourceType, and index when sending to splunk but Im not able to change the index. 
I put the "index" property in my splunkSettings object but I saw in the code from the library that it is not taking that property to replace it in the metadata for splunk.

Is it possible to add this feature?

![Captura de pantalla 2019-04-23 a la(s) 17 40 40](https://user-images.githubusercontent.com/4486150/56620556-f47d8780-65ee-11e9-9fe7-59266da60980.png)

**Comment by winstonspencer** [comment]
I agree, we should be able to send the index also.  How soon can we merge this pull request?

**Comment by adrianhall** [comment]
I just merged PR #10, and released as version 2.2.0.
